/**
 * 前后端统一错误码定义
 * 对齐后端: backend/src/main/java/com/polaris/common/exception/ErrorCode.java
 */

export const ERROR_CODES = {
  // 用户/认证相关
  USER_NOT_FOUND: 2001,
  USERNAME_EXISTS: 2002,
  EMAIL_EXISTS: 2003,
  INVALID_CREDENTIALS: 2004,
  TOKEN_EXPIRED: 2005,

  // 验证码/邮件相关
  CODE_INVALID: 8001,
  CODE_EXPIRED: 8002,
  CODE_USED: 8003,
  CODE_FAILED_TOO_MANY: 8004,
  CODE_PURPOSE_MISMATCH: 8005,
  RATE_LIMIT_EMAIL: 8006,
  RATE_LIMIT_IP: 8007,
  RATE_LIMIT_DAILY: 8008,
  EMAIL_BLOCKED: 8009,
  EMAIL_SEND_FAILED: 8010,
  CODE_GENERATE_FAILED: 8011,
} as const;

export const ERROR_RANGES = {
  AUTH_MIN: 2001,
  AUTH_MAX: 2005,
  VERIFICATION_MIN: 8001,
  VERIFICATION_MAX: 8011,
} as const;

export const RATE_LIMIT_ERROR_CODES = new Set<number>([
  ERROR_CODES.RATE_LIMIT_EMAIL,
  ERROR_CODES.RATE_LIMIT_IP,
  ERROR_CODES.RATE_LIMIT_DAILY,
]);
